name: GitHub Snake

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Executa diariamente às 00:00 (UTC)

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Gerar imagens do GitHub Snake
        uses: Platane/snk@v3
        with:
          # Pode usar a variável do contexto ou o seu nome de usuário diretamente:
          github_user_name: 5kr1pt
          outputs: |
            github-snake.svg
            github-snake-dark.svg?palette=github-dark

      - name: Commit das imagens geradas
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Atualiza GitHub Snake"
          file_pattern: "github-snake*.svg"
